name: Run fix_formatting.py
on: push
jobs: 
  run_formatting: 
    name: Formatting your code
    runs-on: ubuntu-16.04
    steps: 
    - uses: actions/checkout@v2
    - name: Installing formatting tools
      run: |
        pip install --upgrade pip
        pip install pyformat
        sudo apt-get update
        sudo apt-get install clang-format
    - name: Invoking fix_formatting.py
      run: |
        ./utils/fix_formatting.py
    - name: Committing changes
      run: |
        git status
        # TODO
