name: Formatting your code
on: push
jobs:
  run_formatting:
    name: Run fix_formatting.py
    runs-on: ubuntu-16.04 # clang-format has broken dependencies on ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Installing python
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - name: Installing formatting tools
      run: |
        sudo apt-get update
        sudo apt-get install clang-format
        pip install pyformat
    - name: Invoking fix_formatting.py
      run: |
        python3 ./utils/fix_formatting.py
    - name: Gathering changes
      run: |
        nrfiles=$(git status -s | wc -l)
        if [ $nrfiles == 0 ]
        then
          echo "Nothing to do"
          exit 0
        elif [ $nrfiles == 1 ]
        then
          echo "1 file formatted"
          nrfiles=$(git status -s)
          export FILES="'${nrfiles# * }' was"
        else
          echo "$nrfiles files formatted"
          export FILES="$nrfiles were"
        fi
        echo ::set-env name=env.COMMIT_MESSAGE::"$FILES automatically formatted."
        echo ::set-env name=env.BRANCH_NAME::$(git rev-parse --abbrev-ref HEAD)
    - name: THIS STEP IS FOR TESTING ONLY
      run: |
        echo "${env.BRANCH_NAME}"
        if ! [ "${env.BRANCH_NAME}" == "action" ]; then exit 1; fi
    - name: Committing and pushing changes
      uses: stefanzweifel/git-auto-commit-action@v2.5.0
      with:
        commit_message: ${{ env.COMMIT_MESSAGE }}
        branch: ${{ env.BRANCH_NAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
