name: Run fix_formatting.py
on: push
jobs: 
  run_formatting: 
    name: Formatting your code
    runs-on: ubuntu-16.04
    steps: 
    - name: Checkout
      uses: actions/checkout@v2
    - name: Installing python
      uses: actions/setup-python@v1
      with: 
        python-version: 3.x
    - name: Installing formatting tools
      run: |
        sudo apt-get update
        sudo apt-get install clang-format
        pip install pyformat
    - name: Invoking fix_formatting.py
      run: |
        python3 ./utils/fix_formatting.py
    - name: Gathering changes
      run: |
        echo "Test: GITHUB_REF = $GITHUB_REF"
        echo "Test: GITHUB_BASE_REF = $GITHUB_BASE_REF"
        echo "Test: GITHUB_HEAD_REF = $GITHUB_HEAD_REF"
        export nrfiles=$(git status -s | wc -l)
        if [ $nrfiles == 0 ]
        then
          echo "Nothing to do"
          return 0
        fi
        if [ $nrfiles == 1 ]
        then
          export files="$(git status -s) was"
        else
          export files="$nrfiles files were"
        fi
    - name: Committing and pushing changes
      uses: stefanzweifel/git-auto-commit-action@v2.5.0
      with:
        branch: action
        commit_message: "$files automatically formatted."
        commit_options: '--dry-run' '--author="Widelands Formatting Bot"'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
