name: Run fix_formatting.py
on: push
jobs: 
  run_formatting: 
    name: Formatting your code
    runs-on: ubuntu-latest
    steps: 
    - name: Invoking fix_formatting.py
      uses: actions/checkout@v2
      run: |
        ls -a
        cd widelands
        ls -a
