name: Test Suite
on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, edited, reopened, synchronize ]
jobs:
  doc:
    name: Documentation Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Installing python
      uses: actions/setup-python@v1
      with:
        python-version: 3.x
    - name: Installing sphinx
      run: pip install sphinx
    - name: Generating documentation
      run: |
        cd doc/sphinx
        mkdir source/_static
        ./extract_rst.py
        sphinx-build -W -b json -d build/doctrees source build/json
  codecheck:
    name: Codecheck Suite
    # CMake is having trouble detecting too-recent boost versions ATM
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setting up CMake and running codecheck
      run: |
        sudo apt-get update
        sudo apt-get install libboost-dev libboost-regex-dev libboost-system-dev libboost-test-dev libglew-dev libicu-dev libpng-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev zlib1g-dev gettext
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE:STRING="Debug"
        pushd ../cmake/codecheck
        ./run_tests.py
        popd
        TERM=dumb make -j1 codecheck 2>&1 | tee codecheck.out
        if grep '^[/_.a-zA-Z]\+:[0-9]\+:' codecheck.out; then
          echo "You have codecheck warnings (see above), please fix"
          exit 1
        fi
  includes:
    name: Include Sweeping
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Finding superfluous includes and forward declarations
      run: |
        cd src
        ../utils/find_unused_includes.py
